version: '3.8'

services:
  bot:
    build: .
    ports:
      - "8080:8080"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBHOOK_BASE_URL=${WEBHOOK_BASE_URL}
      - MONGO_URI=mongodb://mongo:27017/youtube_shorts_bot
      - OPUS_API_URL=${OPUS_API_URL}
      - OPUS_API_KEY=${OPUS_API_KEY}
      - OPUS_WEBHOOK_SECRET=${OPUS_WEBHOOK_SECRET}
    depends_on:
      - mongo
    volumes:
      - ./logs:/app/logs

  api:
    build: .
    command: python api/main.py
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/youtube_shorts_bot
      - OPUS_WEBHOOK_SECRET=${OPUS_WEBHOOK_SECRET}
      - BOT_TOKEN=${BOT_TOKEN}
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: